version: "3"
services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports: 
      - 5432:5432
    volumes:
    - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
